import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Image from "next/image";

const inter = Inter({ subsets: [ "latin" ] });

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex bg-gray-100 text-gray-500`}>
        <div className="p-5">
          <Image
            src="/logo-vissasa.png"
            width={88}
            height={88}
            alt="Logo Vissasa"
          />

          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
